### ISSUE TITLE
Miss pressing the status flags

### ISSUE THREAD

**Issue by hrvojeerjavec** [Floatist/Floatist-support#14]
Our staff has issues with pressing the right icons in the boat status. 
I would suggest we enforce this with permissions, on the level of each flag. 
It would be great if we can choose who can change each flag. Maybe even increase the size of the icons they can control?

**Comment by yergom** [comment]
I do agree that not everyone should be allowed to change specific states. However, do we really need to have permissions at the flag level? Wouldn't it be enough to have different roles? (ADMIN, BASE_STAFF, CLEANER, TECHNICIAN?). One of the reasons we have still not implemented more roles/permissions is because we still do not have a good picture of what's really required, as I still question myself whether fleet operators need such fine grained permissions, or not. Fine grained permissions give you the ultimate power, but they are also difficult to manage and understand.

**Comment by hrvojeerjavec** [comment]
Maybe it is about terminology, but I see it as the role of a Cleaner will be able to change the flags of "clean outside" and "clean inside". I am giving a feedback of what the problems are in practice, if you like we can go through permissions together, I already sent Cindy some feedback on permission matrix.

For me it is not too difficult to manage permissions, but you can choose a different approach that will solve the problem I mentioned.

**Comment by yergom** [comment]
Permissions will be handled in the future, but for now, we've completely revamped the booking flags. Bigger icons, better swipe behaviours (even in very small screens), and we've also improved the booking detail page, with a stream lines timeline that explains much better what the next steps are.

![image](https://user-images.githubusercontent.com/1982805/235919570-8fcd1411-ee66-497a-99ab-101fd72671a4.png)
