### ISSUE TITLE
Better view of remarks of the boat

### ISSUE THREAD

**Issue by hrvojeerjavec** [Floatist/Floatist-support#19]
When a guest leaves a remark, we need to search it in the inventory list, to see what the guest written. Most of the things are ok, so having a filter of things the guest has remarks about would be very useful.

**Comment by cindyallis** [comment]
Hi @hrvojeerjavec, do you mean in the list that your staff views on mobile, after the client pre-check? Or do you mean on desktop? 

If you mean on mobile, I think we could instead of having the little info which says '2 items with remarks' on the phone we could also add all the remarks in there in a dropdown, just like how the repairs are shown.

**Comment by hrvojeerjavec** [comment]
I meant mobile, I am not sure about desktop. Dropdown sounds right.

**Comment by yergom** [comment]
After some though about what the best UX could be, I've come up with this solution:

![image](https://github.com/Floatist/Floatist-support/assets/1982805/8af4a7a1-51bc-43b4-9e52-cc2829812e5f)

During check-in/check-out, you can now decide whether you want to see all the items, or only the ones with remarks. Choosing the ones with remarks does not filter uncompleted items, nor compulsory items like boat components and signatures. The same switch will be available in the submission page.
