### ISSUE TITLE
Hiding bookings after duplication

### ISSUE THREAD

**Issue by hrvojeerjavec** [Floatist/Floatist-support#20]
We had situations where we needed to adjust the existing booking from MMK. It is related to the https://github.com/Floatist/Floatist-support/issues/4
We couldn't do it in MMK, so we used a different aproach:

Creating duplicate booking with edited properties is a working solution, but since it is a duplicate it can cause confusion of the workers on the pier. They don't know which booking is the "true" booking. 

We need a way to hide a booking if it is duplicated for those purposes. 

A duplicate button could also be very handy to copy all data to new booking. Specially useful when we will have remarks and notes.

**Comment by cindyallis** [comment]
hi @hrvojeerjavec why was it not possible to change it in MMK? Is that expected behaviour? 
To solve the duplicated booking problem when creating an additional booking in Floatist we could probably have a way of 'cancelling' a booking. I will discuss with @yergom and let you know :)

**Comment by yergom** [comment]
@hrvojeerjavec  I'm thinking of a different solution, especially after reading #4. In floatist, every booking has a source. It could be a Floatist source, or MMK, or maybe another 3rd party system in the future. What you are doing here is deviating from mmk, due to its limitations. So, what if we had a way to say: Hey, I know this booking came from mmk, but now I want to deal with it myself. That is, I want Floatist to take ownership of the booking from now onwards. We could still remember the fact that it is linked to an mmk booking (we have it's external id), but make sure that now its source is Floatist. This would imply that you are now free to change any attribute of the booking, and we will not overwrite this data during mmk synchronization. 

Would that work? The added benefit (instead of duplicating) is that the booking is stable, so clients do not need to log in with a different link any more.

**Comment by hrvojeerjavec** [comment]
Sound it could work, but I need to check corner cases. Would that mean after it detaches from MMK it will no longer get updated with changes that are made in MMK? Might not be a problem even if it didn't update, but need to check with booking office.

**Comment by cindyallis** [comment]
@yergom discussed this with Hrvoje and this sounds like it could work. As an example: Adventure Charter currently has a booking of 5 weeks, but in MMK it shows as 4 weeks + 1 week. This booking ideally needs to be shown as one 5 week booking in Floatist, so the above solution you presented would solve it, because then they could do:
- Detach both bookings
- Change end date of the first booking to a week later
- Remove second booking

**Comment by hrvojeerjavec** [comment]
This is better than my suggestion, because the check in is already done, and I would not lose the progress like I would with creating a new booking.

**Comment by yergom** [comment]
I can only think of one corner case. In your exmaple, @cindyallis , if we remove the second booking, then we should still make sure that it's not really deleted, but soft-deleted (which we are already doing), so that we do not synchronize it again with mmk. But it's definitely doable. I think I know then how to proceed.
