### ISSUE TITLE
Deletion of mmk made booking reports success

### ISSUE THREAD

**Issue by hrvojeerjavec** [Floatist/Floatist-support#9]
We were testing the precheckin before the client came, and we got to the point where we confirmed precheckin, and didn't know how to reset it. We created a new booking manually with same information. I wanted to delete the mmk made one, and it reports success but it didn't do anything. I expect the mmk booking should not be deleteable, but the success response from the server is faulty.

**Comment by yergom** [comment]
Delete actions are now disabled for mmk bookings. Our backend is implement batch deletions, and ignoring mmk ones. So, from the point of view of the backend, it's okay to delete mmk bookings, since it's a No-Op. 
Another technical note, our deletions are logical deletions, internally we treat those bookings as being cancelled. We are still not showing cancelled bookings, but at some point we could if required.
